#!/usr/bin/env python3
"""Generate docs/TOOLS.md and docs/TOOL-LICENSING.md from tools/manifest.yaml. Use --check in CI."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages" / "aegis-core"))
from aegis import manifest  # noqa: E402

GEN = "<!-- GENERATED by scripts/gen-tool-docs.py from tools/manifest.yaml. Do not edit by hand. -->\n"


def tools_md(m):
    out = [GEN, "# Tool ecosystem\n",
           "Everything here is derived from `tools/manifest.yaml`. A package name is a *candidate* until it "
           "resolves on a Debian 13 host (`aegis manifest check-packages`). Tiers: core (planned for the ISO), "
           "optional (installable from APT), external, containerized, development, specialized.\n",
           "Offensive-security tools are for **authorized testing and education only**.\n"]
    log = m.raw.get("verification_log", [])
    if log:
        out.append("## Verification log\n")
        out += [f"- {x}" for x in log]
        out.append("")
    for cat, meta in m.categories.items():
        out.append(f"\n## {cat} ({meta['title']})\n")
        out.append("| Tool | Tier | Method | Candidate package | Description |\n|---|---|---|---|---|")
        for t in m.by_category(cat):
            out.append(f"| {t.name} | {t.tier} | {t.installation_method} | {t.package or '-'} | {t.description} |")
    return "\n".join(out) + "\n"


def licensing_md(m):
    out = [GEN, "# Tool licensing\n",
           "## Policy\n",
           "- No license, homepage, source or redistribution fact is recorded unless it was verified from an "
           "official source. Unverified values are written as `unverified`; nothing is guessed.",
           "- `Bundled` means shipped inside the ISO with verified metadata. The validator rejects `bundled: true` "
           "unless the license is verified, redistribution is `allowed`, and the method is `apt`.",
           "- Software with unknown or restrictive redistribution terms (for example proprietary tools) is never "
           "bundled; it is documented as an external installation the user performs from the vendor.",
           "- **ISO package basis (open decision for maintainers):** the ISO enables only the Debian archive areas "
           "`main`, `contrib` and `non-free-firmware`, which the Debian project redistributes. Per-tool license "
           "metadata below is still to be filled in from Debian package copyright files on a Debian host.\n",
           f"## Per-tool record ({len(m.tools)} tools)\n",
           "| Name | License | Homepage | Source | Redistribution | Bundled | Installation | Notes |",
           "|---|---|---|---|---|---|---|---|"]
    for t in m.tools:
        note = t.data.get("notes") or {"external": "no automated install; follow upstream docs",
                "container": "run as a container; image provenance unverified",
                "pipx": "isolated Python environment; upstream unverified"}.get(t.installation_method, "candidate package unverified")
        out.append(f"| {t.name} | {t.license} | {t.homepage} | unverified | {t.redistribution} | "
                   f"{'yes' if t.bundled else 'no'} | {t.installation_method} | {note} |")
    return "\n".join(out) + "\n"


def main():
    m = manifest.load()
    targets = {ROOT / "docs" / "TOOLS.md": tools_md(m), ROOT / "docs" / "TOOL-LICENSING.md": licensing_md(m)}
    if "--check" in sys.argv:
        stale = [p.name for p, c in targets.items() if not p.is_file() or p.read_text() != c]
        if stale:
            print("stale:", ", ".join(stale))
            return 1
        print("up to date")
        return 0
    for p, c in targets.items():
        p.write_text(c, encoding="utf-8")
        print("wrote", p.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
